In [13]:
#Author - Aparna Gupta
#Solution to Selection Test for Network Simulation Position

In [45]:
import numpy as np
from qiskit import QuantumCircuit, assemble, Aer, execute, QuantumRegister, ClassicalRegister
from qiskit.visualization import plot_bloch_multivector, plot_histogram, plot_bloch_vector, plot_state_qsphere, plot_state_city, plot_state_hinton, plot_gate_map, plot_error_map, array_to_latex
from qiskit.circuit import Gate
from math import pi
sim = Aer.get_backend('aer_simulator')
backend = Aer.get_backend('statevector_simulator') # Tell Qiskit how to simulate our circuit

In [40]:
#Task-1
#Question A

#defining the initial states
qc_zero = [1,0]
qc_one = [0,1]
qc_plus = [1/np.sqrt(2), 1/np.sqrt(2)]#plus state
qc_minus = [1/np.sqrt(2), -1/np.sqrt(2)]#minus state
qc_up =  [1/np.sqrt(2), 1j/np.sqrt(2)]#up state
qc_down =  [1/np.sqrt(2), -1j/np.sqrt(2)]#down state

def pauli_gates():
    ''' analyzing the action of standard pauli gate
    on the given initial states'''
    
    states = [qc_zero, qc_one, qc_plus, qc_minus, qc_up, qc_down]
    i = []
    x = []
    y = []
    z = []
    i_hat = [[1,0],[0,1]]#identity gate
    x_hat = [[0,1],[1,0]]#Pauli X-gate
    y_hat = [[0,-1j],[1j,0]]#pauli y- gate
    z_hat = [[1,0],[0,-1]]#pauli z gate

    for vector in states:
        #applictaion of identity gate
        vector = np.tensordot(i_hat,vector,1)
        i.append(vector)
    for vector in states:
        #application of pauli x gate
        vector = np.dot(x_hat,vector)
        x.append(vector)
    for vector in states:
        #application of pauli y gate
        vector = np.dot(vector,y_hat)
        y.append(vector)
    for vector in states:
        #application of pauli z gate
        vector = np.dot(z_hat,vector)
        z.append(vector)

    print(i,'\n',x,'\n',y,'\n',z)
    #returning the final states
pauli_gates()
#action of pauli gates on one basis state



[array([1, 0]), array([0, 1]), array([0.70710678, 0.70710678]), array([ 0.70710678, -0.70710678]), array([0.70710678+0.j        , 0.        +0.70710678j]), array([0.70710678+0.j        , 0.        -0.70710678j])] 
 [array([0, 1]), array([1, 0]), array([0.70710678, 0.70710678]), array([-0.70710678,  0.70710678]), array([0.        +0.70710678j, 0.70710678+0.j        ]), array([0.        -0.70710678j, 0.70710678+0.j        ])] 
 [array([0.+0.j, 0.-1.j]), array([0.+1.j, 0.+0.j]), array([0.+0.70710678j, 0.-0.70710678j]), array([0.-0.70710678j, 0.-0.70710678j]), array([-0.70710678+0.j        ,  0.        -0.70710678j]), array([0.70710678+0.j        , 0.        -0.70710678j])] 
 [array([1, 0]), array([ 0, -1]), array([ 0.70710678, -0.70710678]), array([0.70710678, 0.70710678]), array([0.70710678+0.j        , 0.        -0.70710678j]), array([0.70710678+0.j        , 0.        +0.70710678j])]


In [42]:
#Question B
#c_phase
#c_not

def cnot_gate_implementation(c,t):
    '''application of cnot gate
    args: c - control qubit
          t = target qubit
    returns: final state of the two-qubit system after 
            applying the cnot gate'''
    cnot_gate = [[1,0,0,0],[0,1,0,0],[0,0,0,1],[0,0,1,0]]
    #defining the cnot gate operator
    
    initial_state = np.kron(c,t)
    #defining the intitial state of thw two qubit system
    
    final_state = np.tensordot(initial_state,cnot_gate,1)
    #calculating the final state
    
    return(array_to_latex(final_state, prefix="\\text{final state = }\n"))


In [19]:
def cphase_gate_implementation(c,t):
    '''application of cphase gate
    args: c - control qubit
          t = target qubit
    returns: final state of the two-qubit system after
            applying the cphase gate'''
    
    cphase_gate = [[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,-1]]
    #defining the cphase gate operator

    initial_state = np.kron(c,t)
    #defining the intitial state of thw two qubit system

    final_state = np.tensordot(initial_state,cphase_gate,1)
    #calculating the final state

    return(array_to_latex(final_state, prefix="\\text{final state = }\n"))
    

In [20]:
cnot_gate_implementation(qc_plus,qc_zero)

<IPython.core.display.Latex object>

In [179]:
cnot_gate_implementation(qc_plus,qc_up)

<IPython.core.display.Latex object>

In [180]:
cnot_gate_implementation(qc_plus,qc_down)

<IPython.core.display.Latex object>

In [181]:
cphase_gate_implementation(qc_plus,qc_zero)

<IPython.core.display.Latex object>

In [182]:
cphase_gate_implementation(qc_plus,qc_up)

<IPython.core.display.Latex object>

In [183]:
cphase_gate_implementation(qc_plus,qc_down)

<IPython.core.display.Latex object>

In [184]:
##task C
#mathematical proof
i_hat = [[1,0],[0,1]]
H = [[1/np.sqrt(2), 1/np.sqrt(2)],[1/np.sqrt(2), -1/np.sqrt(2)]]
#defining the hadamard gate

cnot_gate = [[1,0,0,0],[0,1,0,0],[0,0,0,1],[0,0,1,0]]
#defining the cnot gate

i_tens_h = np.kron(i_hat,H)
h_cx = np.tensordot(i_tens_h,cnot_gate,1)
h_cx_h = np.tensordot(h_cx,i_tens_h,1)
#calculating H(CX)H

array_to_latex(h_cx_h, prefix="\\text{final state = }\n")
#printing the result H(CX)H = CZ

<IPython.core.display.Latex object>

In [27]:
##Task D


def bellstates(qubit_zero,qubit_one):
    '''creating bell states using hadamard and cnot gates
    args: qubit_zero - first basis state
          qubit_one - second basis state
    Returns: Bell Pair
    '''
    #defining gate
    i_hat = [[1,0],[0,1]]
    H = [[1/np.sqrt(2), 1/np.sqrt(2)],[1/np.sqrt(2), -1/np.sqrt(2)]]
    cnot_gate = [[1,0,0,0],[0,1,0,0],[0,0,0,1],[0,0,1,0]]

    #defining initial state
    initial_state = np.kron(qubit_zero,qubit_one)

    #applying the hadamard and cnot gate
    h_tens_i = np.kron(H,i_hat)
    entanglement = np.tensordot(h_tens_i,cnot_gate,1)

    #returning bell pairs
    entangled_state = np.tensordot(initial_state,entanglement,1)
    return(entangled_state)    

In [29]:
array_to_latex(bellstates(qc_zero,qc_one), prefix="\\text{bell state = }\n")

<IPython.core.display.Latex object>

In [31]:
array_to_latex(bellstates(qc_zero,qc_zero), prefix="\\text{bell state = }\n")

<IPython.core.display.Latex object>

In [33]:
array_to_latex(bellstates(qc_one,qc_one), prefix="\\text{bell state = }\n")

<IPython.core.display.Latex object>

In [189]:
array_to_latex(bellstates(qc_one,qc_zero), prefix="\\text{bell state = }\n")

<IPython.core.display.Latex object>

In [190]:
#task E
def bellstates_reverse(x):
    '''reversing entanglement using hadamard and cnot gates
    args: x: entangled pair of qubits
    returns: decoded state'''

    #defining gate
    i_hat = [[1,0],[0,1]]
    H = [[1/np.sqrt(2), 1/np.sqrt(2)],[1/np.sqrt(2), -1/np.sqrt(2)]]
    cnot_gate = [[1,0,0,0],[0,1,0,0],[0,0,0,1],[0,0,1,0]]
    
    initial_state = x

    #decoding using hadamard and cnot gate
    h_tens_i = np.kron(H,i_hat)
    dentanglement = np.tensordot(cnot_gate,h_tens_i,1)

    #returns decoded state vector
    dentangled_state = np.tensordot(initial_state,dentanglement,1)
    return(array_to_latex(dentangled_state, prefix="\\text{Decoded state = }\n"))


In [191]:
bellstates_reverse(bellstates(qc_one,qc_zero))

<IPython.core.display.Latex object>

In [192]:
bellstates_reverse(bellstates(qc_one,qc_one))

<IPython.core.display.Latex object>

In [193]:
bellstates_reverse(bellstates(qc_zero,qc_one))

<IPython.core.display.Latex object>

In [194]:
bellstates_reverse(bellstates(qc_zero,qc_zero))

<IPython.core.display.Latex object>

In [195]:
#Task F

#defining basis states

i_hat = [[1,0],[0,1]]
x_hat = [[0,1],[1,0]]
y_hat = [[0,1j],[-1j,0]]
z_hat = [[1,0],[0,-1]]
cnot_gate = [[1,0,0,0],[0,1,0,0],[0,0,0,1],[0,0,1,0]]

def density_operator(x,U):
    ''' Applying the pauli gate to density operators
    args: x - basis state
          U - gate being applied
    returns: resulting density operator after applying the 
    U gate to the density operator of the basis state'''

    #calculating the density operator
    x = np.array(x)
    x = np.conjugate(x)
    x_adj = x.reshape(-1,1)
    rho = np.kron(x,x_adj)

    #defining U and conjugate transpose of U
    U = np.array(U)
    U_conj = np.conj(U)
    U_dagger = np.transpose(U_conj)

    #calculating the resultant density operator
    # by applying U(rho)U_dagg 
    u_rho = np.tensordot(U,rho,1)
    u_rho_udag = np.tensordot(u_rho, U_dagger,1)
    
    return(array_to_latex(u_rho_udag, prefix="\\text{final state = }\n"))

In [196]:
density_operator(qc_plus,i_hat)

<IPython.core.display.Latex object>

In [197]:
density_operator(qc_plus,x_hat)

<IPython.core.display.Latex object>

In [198]:
density_operator(qc_plus,y_hat)

<IPython.core.display.Latex object>

In [199]:
density_operator(qc_plus,z_hat)

<IPython.core.display.Latex object>

In [200]:
density_operator(qc_minus,i_hat)

<IPython.core.display.Latex object>

In [201]:
density_operator(qc_minus,x_hat)

<IPython.core.display.Latex object>

In [202]:
density_operator(qc_minus,y_hat)

<IPython.core.display.Latex object>

In [203]:
density_operator(qc_minus,z_hat)

<IPython.core.display.Latex object>

In [204]:
density_operator(np.kron(qc_plus,qc_up),cnot_gate)

<IPython.core.display.Latex object>

In [205]:
density_operator(np.kron(qc_plus,qc_down),cnot_gate)

<IPython.core.display.Latex object>

In [206]:
#task G
def den_op(x):
    '''calculation of the density operator
    given a basis state x.
    args: x : basis state
    returns: density operator - rho'''
    
    x = np.array(x)
    x = np.conjugate(x)
    x_adj = x.reshape(-1,1)
    rho = np.kron(x,x_adj)
    return(rho)

def adjoint(U):
    '''calculating the conjugate transpose given a matrix U
    args: U - matrix 
    returns: U_dagger - conjugate transpose of U'''
    
    U = np.array(U)
    U_conj = np.conj(U)
    U_dagger = np.transpose(U_conj)
    return(U_dagger)
    
def k_rho_kdag(k,r):
    '''Evaluating the operation of the gate on the
    density operator r.
    args: k: the gate to be applied
          r: density operator
    returns: resultant density vector after applying 
    the k-gate operation
    '''
    
    u_rho = np.tensordot(k,r,1)
    u_rho_udag = np.tensordot(u_rho, adjoint(k),1)
    return(u_rho_udag)
    
def depolarizing_channel(state,p):
    '''evaluating noise in a two qubit quantum system using
    depolarizing channel.
    args: state: basis state 
    p: probability'''

    #defining gates
    i_hat = np.array([[1,0],[0,1]])
    x_hat = np.array([[0,1],[1,0]])
    y_hat = np.array([[0,1j],[-1j,0]])
    z_hat = np.array([[1,0],[0,-1]])

    #defining K - the elements of depolarizing channel
    k_zero = np.sqrt(1-(3*p/4))*i_hat
    k_one = np.sqrt(p/4)*x_hat
    k_two = np.sqrt(p/4)*y_hat
    k_three = np.sqrt(p/4)*z_hat

    #calculating the density operator
    rho = den_op(state)

    #calculating the state after implementing the channel
    l = k_rho_kdag(k_zero,den_op(state))+k_rho_kdag(k_one,den_op(state))+k_rho_kdag(k_two,den_op(state))+k_rho_kdag(k_three,den_op(state))

    #returning the resultant density operator
    return(l)
    
    

In [207]:
qc_plus = [1/np.sqrt(2), 1/np.sqrt(2)]
qc_minus = [1/np.sqrt(2), -1/np.sqrt(2)]

In [208]:
array_to_latex(depolarizing_channel(qc_plus,0))

<IPython.core.display.Latex object>

In [209]:
array_to_latex(depolarizing_channel(qc_plus,0.25))

<IPython.core.display.Latex object>

In [210]:
array_to_latex(depolarizing_channel(qc_plus,0.5))

<IPython.core.display.Latex object>

In [211]:
array_to_latex(depolarizing_channel(qc_plus,0.75))

<IPython.core.display.Latex object>

In [212]:
array_to_latex(depolarizing_channel(qc_plus,1))

<IPython.core.display.Latex object>

In [213]:
array_to_latex(depolarizing_channel(qc_minus,0))

<IPython.core.display.Latex object>

In [214]:
array_to_latex(depolarizing_channel(qc_minus,0.25))

<IPython.core.display.Latex object>

In [215]:
array_to_latex(depolarizing_channel(qc_minus,0.5))

<IPython.core.display.Latex object>

In [216]:
array_to_latex(depolarizing_channel(qc_minus,0.75))

<IPython.core.display.Latex object>

In [217]:
array_to_latex(depolarizing_channel(qc_minus,1))

<IPython.core.display.Latex object>

#task H
def k_operator(order,p):
    '''defining the elements of depolarizing channel for
    two qubit systems.
    args: order - qubit to be modified
          p = probability
    returns - the elements of depolarizing channel'''
    
    if order == 'one':
        k_zero = np.sqrt(1-(3*p/4))*np.kron(i_hat,i_hat)
        k_one = np.sqrt(p/4)*np.kron(x_hat,i_hat)
        k_two = np.sqrt(p/4)*np.kron(y_hat,i_hat)
        k_three = np.sqrt(p/4)*np.kron(z_hat,i_hat)
    elif order == 'two':
        k_zero = np.sqrt(1-(3*p/4))*np.kron(i_hat,i_hat)
        k_one = np.sqrt(p/4)*np.kron(i_hat,x_hat)
        k_two = np.sqrt(p/4)*np.kron(i_hat,y_hat)
        k_three = np.sqrt(p/4)*np.kron(i_hat,z_hat)
    return([k_zero,k_one,k_two,k_three])

def depolarizing_channel_2(state,n,p):
    '''Implementing depolarizing channel for two 
    qubit states.
    args: state - state vector to be modified
          n - qubit to be modified (1 or 2)
          p - probability
    returns - density operator after implementing 
    the depolarizing channel'''

    #defining pauli gates
    i_hat = np.array([[1,0],[0,1]])
    x_hat = np.array([[0,1],[1,0]])
    y_hat = np.array([[0,1j],[-1j,0]])
    z_hat = np.array([[1,0],[0,-1]])
    
    #calculating the depolarizing channel to be implemented
    operator = k_operator(n,p)
    
    #calculating density operator
    rho = den_op(state)

    #returns density operator after implementing the depolarizing channel
    l = k_rho_kdag(operator[0],den_op(state))+k_rho_kdag(operator[1],den_op(state))+k_rho_kdag(operator[2],den_op(state))+k_rho_kdag(operator[3],den_op(state))
    return(l)

def depolarizing_channel_3(state,n,p):
    '''Implementing depolarizing channel for two 
    qubit states.
    args: state - density operator to be modified
          n - qubit to be modified (1 or 2)
          p - probability
    returns - density operator after implementing 
    the depolarizing channel'''

    #defining pauli gates
    i_hat = np.array([[1,0],[0,1]])
    x_hat = np.array([[0,1],[1,0]])
    y_hat = np.array([[0,1j],[-1j,0]])
    z_hat = np.array([[1,0],[0,-1]])
    
    #calculating the depolarizing channel to be implemented
    operator = k_operator(n,p)
    
    #calculating density operator
    rho = den_op(state)

    #returns density operator after implementing the depolarizing channel
    l = k_rho_kdag(operator[0],(state))+k_rho_kdag(operator[1],(state))+k_rho_kdag(operator[2],(state))+k_rho_kdag(operator[3],(state))
    return(l)



In [219]:
l= depolarizing_channel_2(bellstates(qc_zero,qc_one),'one',0.5)
l

array([[0.125+0.j, 0.   +0.j, 0.   +0.j, 0.   +0.j],
       [0.   +0.j, 0.375+0.j, 0.25 +0.j, 0.   +0.j],
       [0.   +0.j, 0.25 +0.j, 0.375+0.j, 0.   +0.j],
       [0.   +0.j, 0.   +0.j, 0.   +0.j, 0.125+0.j]])

In [220]:
depolarizing_channel_2(bellstates(qc_zero,qc_one),'two',0.5)

array([[0.125+0.j, 0.   +0.j, 0.   +0.j, 0.   +0.j],
       [0.   +0.j, 0.375+0.j, 0.25 +0.j, 0.   +0.j],
       [0.   +0.j, 0.25 +0.j, 0.375+0.j, 0.   +0.j],
       [0.   +0.j, 0.   +0.j, 0.   +0.j, 0.125+0.j]])

In [221]:
depolarizing_channel_3(l,'two',0.5)

array([[0.1875+0.j, 0.    +0.j, 0.    +0.j, 0.    +0.j],
       [0.    +0.j, 0.3125+0.j, 0.125 +0.j, 0.    +0.j],
       [0.    +0.j, 0.125 +0.j, 0.3125+0.j, 0.    +0.j],
       [0.    +0.j, 0.    +0.j, 0.    +0.j, 0.1875+0.j]])

In [222]:
def entanglement_swapping(x,y):
    '''
    swaps entangelement
    args: x: bell state 1
          y: bell state 2
    returns: swap: state vector after swapping entanglement'''
    
    #defining gates
    i_hat = np.array([[1,0],[0,1]])
    x_hat = np.array([[0,1],[1,0]])
    y_hat = np.array([[0,1j],[-1j,0]])
    z_hat = np.array([[1,0],[0,-1]])
    cnot_gate = [[1,0,0,0],[0,1,0,0],[0,0,0,1],[0,0,1,0]]

    #entanglement swapping
    state_vector = np.kron(x,y)
    I_tens_H = np.kron(i_hat,H)
    I_tens_I = np.kron(i_hat,i_hat)
    I_tens_cx = np.kron(i_hat,cnot_gate)
    s1 = np.kron(I_tens_H,I_tens_I)
    s2 = np.kron(I_tens_cx,i_hat)
    U = np.tensordot(s1,s2,1)

    #return the final state after swapping the entanglement
    swap = np.tensordot(state_vector,U,1)
    return(swap)

(entanglement_swapping(bellstates(qc_zero,qc_one),bellstates(qc_one,qc_zero)))

array([ 0.35355339,  0.        ,  0.        , -0.35355339,  0.        ,
        0.35355339, -0.35355339,  0.        ,  0.35355339,  0.        ,
        0.        , -0.35355339,  0.        , -0.35355339,  0.35355339,
        0.        ])

In [223]:
def entanglement_swapping_2(x,y):
    '''
    swaps entangelement after the first bell state ha
    args: x: bell state 1
          y: bell state 2
    returns: swap: state vector after swapping entanglement'''
    
    #initializing bell states x and y
    state_vector = np.kron(x,y)
    
    #depolarizing the first bell state with p =0.25
    l = depolarizing_channel_2(x,'one',0.25)
    L = depolarizing_channel_3(l,'two',0.25)

    #calculating state vector after making it go through thedepolarizing channel
    state_vector_2 = np.kron(l,y)

    #entanglement swapping
    I_tens_H = np.kron(i_hat,H)
    I_tens_I = np.kron(i_hat,i_hat)
    I_tens_cx = np.kron(i_hat,cnot_gate)
    s1 = np.kron(I_tens_H,I_tens_I)
    s2 = np.kron(I_tens_cx,i_hat)
    U = np.tensordot(s1,s2,1)

    #return the final state after swapping the entanglement
    swap = np.tensordot(state_vector_2,U,1)
    return(l)


(entanglement_swapping_2(bellstates(qc_zero,qc_one),bellstates(qc_one,qc_zero)))



array([[0.0625+0.j, 0.    +0.j, 0.    +0.j, 0.    +0.j],
       [0.    +0.j, 0.4375+0.j, 0.375 +0.j, 0.    +0.j],
       [0.    +0.j, 0.375 +0.j, 0.4375+0.j, 0.    +0.j],
       [0.    +0.j, 0.    +0.j, 0.    +0.j, 0.0625+0.j]])